#!/bin/sh

actions=$(find * -maxdepth 1 -name "action.yml")

for action in $actions; do
    action_name=$(dirname $action)

    echo "Building \"$action_name\" action..."
    pushd "$action_name" >/dev/null
    npm run build
    git add "dist/index.js"
    popd >/dev/null
    echo
done
