#!/bin/sh

packages=$(find * -maxdepth 1 -name "package.json")

for package in $packages; do
    package_name=$(dirname $package)

    echo "Building \"$package_name\" action..."
    pushd "$package_name" >/dev/null
    npm run build
    git add "dist/index.js"
    popd >/dev/null
    echo
done
